a little refactoring

diff --git a/src/contents/MacOS/Photos Server b/src/contents/MacOS/Photos Server
--- a/src/contents/MacOS/Photos Server
+++ b/src/contents/MacOS/Photos Server
@@ -18,6 +18,11 @@
 # (`+`) tilde (`~`) and period (`.`) characters with spaces. If more
 # than one media item is found, a random one will be selected.
 
+# Three known error codes:
+#   104: request to Photos timed out (TIMEOUT NOT IMPLEMENTED)
+#   102: failed to read exported file (likely a PHOTOS ERROR)
+#   100: failed to create temporary directory (SYSTEM ERROR)
+
 ## This file is named `Photos Server` so that's how it will appear
 ## in the notification center's warning about background tasks.
 ##
@@ -60,7 +65,7 @@ open_url(){
 # EXITS
 # &1< HTTP request
 handle_http_request(){
-	read -r _ path _
+	read -r _ path _  # GET <PATH> HTTP/1.1
 	log info "Request: $path"
 	TEMP_DIR="$(mktemp -d -t $TEMP_TEMPLATE)" || die NO_TEMP
 	trap 'cleanup $?' EXIT
@@ -118,8 +123,6 @@ open_media_item(){
 jxa(){
 	{
 		{
-
-
 			osascript -l JavaScript <<-EOF
 const photos = Application("Photos");
 const decodeQuery = (identifier) => identifier?.replace(/[+.~]/g, " ");
@@ -159,42 +162,69 @@ if ( identifier
 	} 3>&1
 }
 
-# EXITS CLEAN TO TRAP or UNCLEAN UNTRAPPED (called by trap)
+# LOG ERROR, RETURN ERR RESPONSE, THEN CLEAN UP
 # $1: enum
 # $2: exit code if unknown error
 die(){
 	case "$1" in
 	NO_MATCH)
 		log "notice" "No matching media item found."
-		svg "404 Not Found" "$missing_svg" "missing"
-		exit 0;;
+		err 404
+		cleanup 0 0;; # exit status 0, not a server error.
 	NO_TIME)
 		log "err" "Request to Photos timed out."
-		svg "504 Gateway Timeout" "$timeout_svg" "timeout"
-		exit 0;;
-	NO_TEMP)
-		log "alert" "Failed to create temporary directory.";;
+		err 504
+		cleanup 0 104;;
 	NO_EXPORT)
-		log "err" "Failed to read exported file.";;
+		log "err" "Failed to read exported file."
+		err 502
+		cleanup 0 102;;
+	NO_TEMP)
+		log "alert" "Failed to create temporary directory."
+		err 500
+		cleanup 0 100;;
 	*)
-		log "alert" "Uncaught error: $2";;
+		log "alert" "Uncaught error: $1"
+		err 500
+		cleanup 0 "$1"
 	esac
-	svg "500 Internal Server Error" "$error_svg" "error"
-	exit "${2:-0}"
 }
 
-# $1: exit code
+
+# WRITES TO SYSTEM LOGGER
+#  0: on success
+# $1: debug | info | notice | err | alert
+# $2: message
+log(){ logger -s -p "user.$1" "[$LOGGER_TAG] $2"; }
+# log(){ echo "[$1] $2">&2;}
+
+
+# PRINT NOT-OK HTTP RESPONSE
+# $1: http error code to respond with
+err(){
+	case "$1" in
+	404) svg "404 Not Found" "$missing_svg" "404_missing" ;;
+	500) svg "500 Internal Server Error" "$error_svg" "500_error";;
+	502) svg "502 Bad Gateway" "$missing_svg" "502_gateway";;
+	504) svg "504 Gateway Timeout" "$timeout_svg" "504_timeout"
+	esac
+}
+
+# REMOVE TEMPORARY DIRECTORY AND EXIT, catching UNKNOWN ERRORS
+# $1: non-0 means it was caught by the trap on non-0 exit
+# $2: exit code for known error when calling cleanup directly
 # shellcheck disable=SC2329  # called from a trap
 cleanup(){
 	trap - EXIT
-	if test -d "$TEMP_DIR"
-	then rm -rf "$TEMP_DIR"
-	fi
-	if test "${1:-0}" -ne 0
-	then die UNKNOWN "$1"
-	fi
+	! test -d "$TEMP_DIR" || rm -rf "$TEMP_DIR"
+	test "$1" -eq 0 || die "$1"
+	exit "${2:-0}"
 }
 
+# PRINT SVG  HTTP RESPONSE
+# $1: http error code to respond with
+# $2: svg data string
+# $3: filename for content
 svg(){
 	printf 'HTTP/1.1 %s\r\n' "$1"
 	printf 'Connection: close\r\n'
@@ -203,18 +233,6 @@ svg(){
 	printf 'Content-Disposition: inline; filename=%s.svg\r\n' "$3"
 	printf '\r\n%s' "$2"
 }
-
-# WRITES TO SYSTEM LOGGER
-#  0: on success
-# $1: one of
-#   debug   intermediate values
-#   info    regular activity (200)
-#   notice  irrecgular activity (404)
-#   err     error fetching request (500)
-#   alert   things that should never happen
-# $2: message
-log(){ logger -s -p "user.$1" "[$LOGGER_TAG] $2"; }
-# log(){ echo "[$1] $2">&2;}
 
 missing_svg='<?xml version="1.0" encoding="UTF-8"?>
 <!-- old school pixellated netscape broken image icon -->
