fix port-forwarding scripts

diff --git a/scripts/__enable-port-forwarding b/scripts/__enable-port-forwarding
--- a/scripts/__enable-port-forwarding
+++ b/scripts/__enable-port-forwarding
@@ -3,9 +3,12 @@
 set -eu
 
 source_dir="$(git rev-parse --show-toplevel)/src/port-forwarding"
-plist_file="ca.heckman.PhotosServer.port-forwarding.plist"
+
+label="ca.heckman.PhotosServer.port-forwarding"
+anchor="com.apple/ca.heckman.PhotosServer"
 
 # these should not be changed
+plist_file="$label.plist"
 source_plist="$source_dir/$plist_file"
 installed_launch_daemon="/Library/LaunchDaemons/$plist_file"
 
@@ -19,10 +22,12 @@ fi
 if \
 sudo cp -i "$source_plist" "$installed_launch_daemon"
 then
-	sudo launchctl unload "$installed_launch_daemon" >/dev/null 2>&1
-	sudo launchctl load -w "$installed_launch_daemon" &&
-	plutil -extract ProgramArguments.2 raw "$installed_launch_daemon" |
-	sed -E 's/^.* ([0-9.]*) port ([0-9]*) -> ([0-9.]*) port ([0-9.]*).*$/Rewuests to \1:\2 should now be forwarded to \3:\4/' &&
+	# this will fail if the daemon isn't actually loaded
+	sudo launchctl bootout "system/$label" >/dev/null 2>&1 || :
+	# not that the daemon is definately not loaded this should not fail
+	sudo launchctl bootstrap system  "$installed_launch_daemon" &&
+	sudo pfctl -q -a "$anchor" -s nat |
+	sed -E 's/^.* ([0-9.]*) port[ =]*([0-9]*) -> ([0-9.]*) port ([0-9.]*).*$/Requests to \1:\2 should now be forwarded to \3:\4/' &&
 	exit 0
 fi
 echo Port-forwarding failed or aborted.
