rewrite

diff --git a/src/photos-http-handler b/src/photos-http-handler
--- a/src/photos-http-handler
+++ b/src/photos-http-handler
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/opt/homebrew/bin/bash
 # Copyright (c) 2024 Erik Ben Heckman, shared under the GPL-3.0 license
 # except where otherwise noted
 # <https://github.com/heckman/photos-server>
@@ -13,117 +13,157 @@
 # path is either the UUID of a media item in Apple Photos or a
 # search query.
 #
-# If a UUID is provided and matches the id of a media item in the
-# Photos library, the media item is served. If the UUID is
-# invalid, a 404 error is returned.
+# If a matching media item is found, it prints, to stdout, a HTTP
+# response with the media item as inline content. If multiple
+# matching media items are found, an arbitrary one is chosen.
 #
-# A provided query will generate a search by Apple Photos for
-# matching photos. (It is limited to photos). Among the results, a
-# random one will be served. If the search comes up empty, a 404 error is returnd.
+# IF no item is found, or Apple Photos times out during the request,
+# then a 404 HTTP response is printed with a placeholder image.
 #
-# If the search takes longer than a preset timeout, or one specified
-# on the command line, a 500 error is returned.
-#
-# If the second element of the path is "open" then Apple Photos is
-# also launched, with specified/queried media item "spotlighted".
-# Note that if the media item is determined by a search, then tho
-# one "spotlighted" and returned via HTTP might be different photos!
-#
-#
-# requires: trurl  (available via homebrew)
+# If something unexpected occurs, a 500 HTTP resonse is printed
+# with a placeholder image.
 
-TRURL=/opt/homebrew/bin/trurl
-PHOTOS_CLI=/usr/local/bin/photos-cli
+set -e
 
-DEFAULT_TIMEOUT_SECONDS=1
-
-
+# dependencies can be installed via homebrew:
+#   brew bash install jq coreutils
+#
+# when this handleris run the ath is /usr/bin:/bin:/usr/sbin:/sbin
+# so we need to locate out dependencies
+TIMEOUT=/opt/homebrew/bin/timeout
+JQ=/opt/homebrew/bin/jq
+# the location of bash also needs to be specified in the shebang
+# bash needs to support associative arrays, which is in bash 4.0
 
 TEMP_TEMPLATE=ca.heckman.photos-server.image
-STDLOG=/dev/null
-
-ERR_PHOTOS_TIMEOUT=143  # error generated by photos-cli
-# ERR_TIMEOUT=124  # generated by `timeout` command, currently not in use
-ERR_EXPORT=144  # arbitrary value, thrown when exported file can't be read
+TIMEOUT_SECONDS=12  # time given to Photos to respond to request
 
 main(){
-  # ignore the rest of the request handlers
-  dispatch_request "$(awk '{print $2;exit}')" # does not return
-  # shellcheck disable=SC2317  # unreachable code
-  exit 1 # should not be reachable
+	local method path protocol
+	# shellcheck disable=SC2034  # not using method or protocol
+	read -r method path protocol
 
-}
+	local -a url_components
+	while read -r part
+	do
+		part="${part//[+.~]/ }"
+		url_components+=("$(printf '%b' "${part//%/\\x}")")
+	done < <(tr / $'\n' <<< "$path")
 
-dispatch_request(){ local request_url="$1" path op
-  path="$($TRURL --get '{path}' "stub.domain/${request_url#/}" | sed 's|^/||')"
-  op="$($TRURL --get '{query}' "stub.domain/${request_url#/}")"
-  [[ "$path" = "favicon"* ]] && exit 0
-  case "$op" in
-  "open")
-    serve "$path" "--open" ;;
-  *)
-    serve "$path";;
-  esac
-  # shellcheck disable=SC2317  # unreachable code
-  exit 1 # should not be reachable
-}
+	local query="${url_components[1]}"
+	local basename="${url_components[-1]}"
 
-serve(){ local query="$1" options="${2:-}"
-  tmpdir="$(mktemp -d -t $TEMP_TEMPLATE)" && trap "rm -rf '$tmpdir'" EXIT
+	debug "Query: $query"
+	debug "Basename: $basename"
 
-	# shellcheck disable=SC2086
-	"$PHOTOS_CLI" export $options "$query" "$tmpdir" >/dev/null || error "$?: $PHOTOS_CLI export $options '$query' '$tmpdir'"
+	local tmpdir
+	tmpdir="$(mktemp -d -t $TEMP_TEMPLATE)" || die ERR_TEMP
+	# shellcheck disable=SC2064  # we want to expand tmpdir now
+	trap "rm -rf '$tmpdir'" EXIT
 
-	filename="$(a_file_in "$tmpdir")" || error $ERR_EXPORT
+	local result
+	result="$(export_media_item_from_photos "$query" "$tmpdir")" ||
+		case $? in
+		1) die ERR_JXA ;;
+		124) not_found "Request to Photos timed out." ;;
+		*) die ;;
+		esac
+
+	debug "Result=$result"
+	[[ -n "$result" ]] || not_found "No matching media items."
+
+	local filename filesize filetype extension
+	filename="$(any_file_in "$tmpdir")" || die ERR_EXPORT
 	filesize="$(stat -f'%z' "$filename")"
 	filetype="$(file -b --mime-type "$filename")"
-	basename="$(basename "$filename")"
+	extension="${filename##*.}"
+
+	debug "Serving 200 OK: $basename.$extension"
 
 	echo "HTTP/1.1 200 OK
 Content-Type: $filetype
 Content-Length: $filesize
-Content-Disposition: inline; filename=$basename
+Content-Disposition: inline; filename=$basename.$extension
 "; cat "$filename";
 
 	exit 0
 }
 
-error(){
-	log 'Error: %s\n' "$1"
-	# shellcheck disable=SC2254  # these are integers
-	case "$1" in
-	$ERR_TIMEOUT|$ERR_PHOTOS_TIMEOUT|$ERR_EXPORT)
-		status="500 Internal Server Error"
-		filename="error.svg"
-		svg="$error_svg";;
-	*)
-		status="404 Not Found"
-		filename="missing.svg"
-		svg="$missing_svg";;
-	esac
-	echo -n "HTTP/1.1 $status
-Content-Type: svg+xml
-Content-Length: ${#svg}
-Content-Disposition: inline; filename=$filename
-
-$svg";
-exit 1
+not_found(){
+	debug "$1"
+	canned_response "404 Not Found" "missing.svg"
+	exit 0
 }
 
+die(){
+	local -A error_messages=(
+		[ERR_TEMP]="Failed to create temporary directory"
+		[ERR_JXA]="Failed to run jxa"
+		[ERR_EXPORT]="Failed to find exported file"
+	)
+	error "${error_messages[$1]:-Unknown error}"
+	canned_response "500 Internal Server Error" "error.svg"
+	exit 1
+}
 
-a_file_in(){
+canned_response(){ local status="$1" filename="$2"
+	local content="${canned_responses[$2]}"
+	local length="${#content}"
+	# all canned responses are svg images
+	local content_type="svg+xml"
+
+	debug "Serving $status: $filename"
+
+	echo -n "HTTP/1.1 $status
+Content-Type: $content_type
+Content-Length: $length
+Content-Disposition: inline; filename=$filename
+
+$content";
+}
+
+any_file_in(){
 	find "$1" -maxdepth 1 -type f ! -name '.*' 2>/dev/null | grep -F ''
 }
 
+debug(){ echo "Debug: $1" >&2; }
+error(){ echo "Error: $1" >&2; }
 
-log(){
-  if test -z "$1"
-  then cat - >>$STDLOG
-  else { printf -- '-> '; printf -- "$@"; } >>$STDLOG
-  fi
+export_media_item_from_photos(){ local query="$1" tmpdir="$2"
+	local jxa="$(cat <<EOF
+(
+	(args)=>{
+		app=Application("Photos");
+		exportItem=(item)=>{
+			app.export(
+				[item], {
+					to:Path(args[1]),
+					usingOriginals: false
+				}
+			)
+		}
+		try{
+			exportItem(app.mediaItems.byId(args[0]))
+			return true
+		} catch {
+			try {
+				exportItem(app.search({for:args[0]})[0])
+				return true
+			} catch {
+				return
+			}
+		}
+	}
+)( $("$JQ" -Rn '[inputs]' <<<"$query
+$tmpdir") )
+EOF
+)"
+	# debug "$jxa"
+	"$TIMEOUT" "$TIMEOUT_SECONDS" /usr/bin/osascript -l JavaScript -e "$jxa"
 }
 
-missing_svg='<?xml version="1.0" encoding="UTF-8"?>
+declare -A canned_responses=(
+	["missing.svg"]='<?xml version="1.0" encoding="UTF-8"?>
 <!-- old school pixellated netscape broken image icon -->
 <!--
   icon created for Netscape Navigator by Marsh Chamberlin (https://dataglyph.com)
@@ -161,8 +201,7 @@ missing_svg='<?xml version="1.0" encoding="UTF-8"?>
   </g>
 </svg>
 '
-
-error_svg='<?xml version="1.0" encoding="UTF-8"?>
+	["error.svg"]='<?xml version="1.0" encoding="UTF-8"?>
 <!--
 The "Sad Mac" icon was created for Apple Inc. by Susan Kare https://kareprints.com
 The SVG was hand-coded Erik Ben Heckman https://erik.heckman.ca
@@ -182,5 +221,8 @@ and can be found embedded in the code for https://github.com/heckman/photos-serv
     M21,25 h6 v1 h-6 Z"></path>
 </svg>
 '
+)
 
 main "$@"
+
+
