a lot

diff --git a/src/photos-http-handler b/src/photos-http-handler
--- a/src/photos-http-handler
+++ b/src/photos-http-handler
@@ -25,6 +25,11 @@
 
 set -e
 
+# shellcheck disable=SC2034
+silent=0  error=1 warn=3 info=4 debug=5
+vebosity=$info
+
+
 # dependencies can be installed via homebrew:
 #   brew bash install jq coreutils
 #
@@ -38,10 +43,13 @@ JQ=/opt/homebrew/bin/jq
 TEMP_TEMPLATE=ca.heckman.photos-server.image
 TIMEOUT_SECONDS=12  # time given to Photos to respond to request
 
+
 main(){
 	local method path protocol
 	# shellcheck disable=SC2034  # not using method or protocol
 	read -r method path protocol
+
+	info "Request path: $path"
 
 	local -a url_components
 	while read -r part
@@ -64,13 +72,17 @@ main(){
 	local result
 	result="$(export_media_item_from_photos "$query" "$tmpdir")" ||
 		case $? in
+		124) die ERR_TIMEOUT 504;;
 		1) die ERR_JXA ;;
-		124) not_found "Request to Photos timed out." ;;
 		*) die ;;
 		esac
 
 	debug "Result=$result"
-	[[ -n "$result" ]] || not_found "No matching media items."
+	[[ -n "$result" ]] || {
+		info "No matching media items."
+		canned_response 404
+		exit 0
+	}
 
 	local filename filesize filetype extension
 	filename="$(any_file_in "$tmpdir")" || die ERR_EXPORT
@@ -78,7 +90,7 @@ main(){
 	filetype="$(file -b --mime-type "$filename")"
 	extension="${filename##*.}"
 
-	debug "Serving 200 OK: $basename.$extension"
+	info "Serving 200 OK: $basename.$extension"
 
 	echo "HTTP/1.1 200 OK
 Content-Type: $filetype
@@ -89,32 +101,41 @@ Content-Disposition: inline; filename=$basename.$extension
 	exit 0
 }
 
-not_found(){
-	debug "$1"
-	canned_response "404 Not Found" "missing.svg"
-	exit 0
-}
+
 
 die(){
 	local -A error_messages=(
 		[ERR_TEMP]="Failed to create temporary directory"
 		[ERR_JXA]="Failed to run jxa"
 		[ERR_EXPORT]="Failed to find exported file"
+		[ERR_TIMEOUT]="Request to Photos timed out."
 	)
 	error "${error_messages[$1]:-Unknown error}"
-	canned_response "500 Internal Server Error" "error.svg"
+	canned_response "${2:-500}"
 	exit 1
 }
 
-canned_response(){ local status="$1" filename="$2"
+canned_response(){
+	local description filename
+	case "$1" in
+	404)
+		description="Not Found"
+		filename="missing.svg";;
+	500)
+		description="Internal Server Error"
+		filename="error.svg";;
+	504)
+		description="504 Gateway Timeout"
+		filename="timeout.svg";;
+	esac
 	local content="${canned_responses[$2]}"
 	local length="${#content}"
 	# all canned responses are svg images
 	local content_type="svg+xml"
 
-	debug "Serving $status: $filename"
+	info "Serving $1: $filename"
 
-	echo -n "HTTP/1.1 $status
+	echo -n "HTTP/1.1 $1 $description
 Content-Type: $content_type
 Content-Length: $length
 Content-Disposition: inline; filename=$filename
@@ -126,8 +147,10 @@ any_file_in(){
 	find "$1" -maxdepth 1 -type f ! -name '.*' 2>/dev/null | grep -F ''
 }
 
-debug(){ echo "Debug: $1" >&2; }
-error(){ echo "Error: $1" >&2; }
+log(){ date +"%Y-%m-%d %H:%M:%S $1" >&2; }
+debug(){ [[ $vebosity -lt $debug ]] || log "[ DEBUG ]  $1"; }
+info(){ [[ $vebosity -lt $info ]] || log "[ INFO ]  $1"; }
+error(){ [[ $vebosity -lt $error ]] || log "[ ERROR ]  $1"; }
 
 export_media_item_from_photos(){ local query="$1" tmpdir="$2"
 	local jxa="$(cat <<EOF
@@ -158,7 +181,7 @@ export_media_item_from_photos(){ local query="$1" tmpdir="$2"
 $tmpdir") )
 EOF
 )"
-	# debug "$jxa"
+	debug "$jxa"
 	"$TIMEOUT" "$TIMEOUT_SECONDS" /usr/bin/osascript -l JavaScript -e "$jxa"
 }
 
